FROM nginx:alpine

LABEL org.opencontainers.image.source https://github.com/swagateam/taskboardfe

RUN apk add --no-cache bash

COPY ./nginx /etc/nginx
COPY wait-for-it.sh .
RUN chmod +x wait-for-it.sh

CMD ["nginx", "-g", "daemon off;"]